version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: "develop"
  labels:
    - "pip dependencies"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
    - "npm dependencies"
