server:
  # The IP from where the service is accessible
  host: 0.0.0.0
  # The port used by the server
  port: 2020

player:
  # Fill the background with black to not see what's behind the player.
  hide_background : True
  # Loop the last video until a new one becomes available.
  loop_last       : True
  # The maximum number of files on disk.
  history_size    : 15

downloader:
  # The directory used to store downloaded videos.
  output_directory: /tmp

subtitle:
  # The default language for subtitles.
  language: eng
