[project]
name = "Opencast"
dynamic = [ "version", "dependencies" ]
description = "A client-server media player that transforms your Raspberry Pi into an awesome streaming device"
license = "MIT"
readme = 'README.md'

requires-python = ">=3.9"

authors = [
  { name = "Luc Sinet", email="<luc.sinet@gmail.com>" },
]
maintainers = [
  { name = "Luc Sinet", email="<luc.sinet@gmail.com>" },
]
repository = "https://github.com/Tastyep/Pi-OpenCast"
keywords = ['raspberry', 'opencast', 'chromecast']

[project.scripts]
my-script = 'OpenCast:main'

[tool.poetry]
version = "1.4.4"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
"hurry.filesize" = "^0.9"
transitions = "^0.8.6"
structlog = "^20.2.0"
colorama = "^0.4.4"
python-vlc = "^3.0.9113"
aiohttp = "^3.7.3"
janus = "^0.6.1"
aiohttp-middlewares = "^2.0.0"
tinydb = "^4.4.0"
marshmallow = "^3.9.1"
marshmallow_enum = "^1.5.1"
aiohttp-apispec = "^2.2.1"
dynaconf = "^3.1.2"
yt-dlp = "*" # Always get the latest available 
MarkupSafe = "2.0.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
pytest-cov = "^2.11"
sphinx_rtd_theme = "^0.5.1"
sphinx = "^4.4.0"
mypy = "^1.5"
sphinx-autodoc-typehints = "^1.11.1"
sphinxcontrib-openapi = "^0.7.0"
mistune = "<2.0.0"
flake8 = "^7.2.0"
isort = "^5.10.1"
coverage = "^5.4"
sphinxemoji = "^0.1.8"
black = "^22.3.0"

[tool.isort]
profile = "black"
src_paths = ["OpenCast", "test"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "NOTSET"
