# Convert JSON Schema-proper to OpenAPI-flavoured Schema Objects
jsonSchema: true
# Keep the noise down
quiet: false
# Output a lot of information about what is happening (wont work if you have quiet on)
# Default stdout = 1
verbose: 1
# Rules specific to the lint command
lint:
  # rules files to load
  rules:
    - strict
  # rules to skip
  skip:
    - info-contact
# Rules specific to the serve command
serve:
  port: 8001
