swagger: "2.0"

info:
  description: The API for sending requests to Opencast
  version: "0.0.0"
  title: OpenCast API

host: "locahost"
tags:
  - name: "video"
    description: "Media queued for playing"
schemes:
  - "http"

paths:
  /videos:
    $ref: ./paths/videos.yml
  /videos/{id}:
    $ref: ./paths/video.yml
