openapi: "3.0.0"

info:
  description: The API for sending requests to Opencast
  version: "0.0.0"
  title: OpenCast API

servers:
  - url: http://localhost:2020/api
tags:
  - name: "video"
    description: "Media queued for playing"
schemes:
  - "http"

paths:
  /videos:
    $ref: "./paths/video.yml#/root"
  /videos/{id}:
    $ref: "./paths/video.yml#/id"
