swagger: "2.0"

info:
  version: "1.0.0"
  title: OpenCast API
  description: The API for sending requests to Opencast

paths:
  /videos:
    get:
      summary: List Videos
      description: |
        Retrieves a list of all videos on file in the host.
      responses:
        200:
          description: An array of Videos
          schema:
            type: array
            items:
              $ref: "#/definitions/Video"
  /videos/{id}:
    get:
      summary: Show Requested Video
      description: |
        Queries and returns a video with a given ID.
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
          description: |
            ID of the video to query.
      responses:
        200:
          description: The video.
          schema:
            $ref: "#/definitions/Video"
        404:
          description: Video not found.
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Remove Requested Video
      description: |
        Remove a video with a given ID.
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
          description: |
            ID of the video to remove.
      responses:
        204:
          description: No content.
        404:
          description: Video not found.
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    properties:
      code:
        type: string
        description: A uniqe identifier of error.
      message:
        type: string
        description: A human readable error message.
  Stream:
    type: object
    properties:
      index:
        type: integer
        format: int32
        description: Stream index
      type:
        type: string
        description: Stream type
      language:
        type: string
        description: Stream language
  Video:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique ID for a video
      source:
        type: string
        description: The source URL of the media
      playlist_id:
        type: integer
        format: int64
        description: Unique ID for a playlist
      thumbnail:
        type: string
        description: A URL to the thumbnail of the media
      title:
        type: string
        description: The title of the media
      path:
        type: string
        description: The path of the file on disk
      streams:
        type: array
        items:
          $ref: "#/definitions/Stream"
