name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      #
      - name: Install dependencies
        run: ./setup.sh --ci
      #
      - name: Test
        run: ./OpenCast.sh test all --coverage
      #
      - name: Coverage upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
